// Generated by TypeScript
/// <reference path="../../../dota.d.ts" />
/// <reference path="itemslot.ts" />
(function () {
    var ItemDB = {
        587: "default",
        10150: "dire",
        10324: "portal",
        10346: "mana_pool"
    };
    var currentUnit = Players.GetLocalPlayerPortraitUnit();
    function onSteamInventoryChanged(event) {
        var skinName = ItemDB[event.itemdef];
        $.Msg(skinName);
        if (skinName !== undefined) {
            $("#spacer").style.backgroundImage = "url('s2r://panorama/images/hud/" + skinName + "/inventory/spacer.png');";
            //WTF DO WE DO NOW WITH DIFFERENT RESOLUTIONS!!
            $("#rocks").style.backgroundImage = "url('s2r://panorama/images/hud/" + skinName + "/inventory/rocks_16_9.png');";
            $("#background").style.backgroundImage = "url('s2r://panorama/images/hud/" + skinName + "/inventory/background_wide.png');";
        }
        $.Msg(event);
    }
    function onUnitChanged(event) {
        onInventoryChanged(event);
        if (Players.GetPlayerHeroEntityIndex(Players.GetLocalPlayer()) != Players.GetLocalPlayerPortraitUnit()) {
            //$.Msg(Players.GetQueryUnit(Players.GetLocalPlayer()), " = ", Players.GetLocalPlayerPortraitUnit());
            $("#stats").SetHasClass("Hidden", true);
        }
        else {
            $.Msg(Players.GetQueryUnit(Players.GetLocalPlayer()), " != ", Players.GetLocalPlayerPortraitUnit());
            $("#stats").SetHasClass("Hidden", false);
        }
        currentUnit = Players.GetQueryUnit(Players.GetLocalPlayer());
    }
    function onInventoryChanged(event) {
        for (var _i = 0, items_1 = items; _i < items_1.length; _i++) {
            var item = items_1[_i];
            item.update();
        }
    }
    function onGoldChanged(event) {
        $("#goldCount").text = Players.GetGold(Players.GetLocalPlayer()).toString(); //TODO: handle selecting allied units.
    }
    function onShopChanged(event) {
        if (event.shopmask > 0) {
            $("#shop").AddClass("ShopActive");
        }
        else {
            $("#shop").RemoveClass("ShopActive");
        }
        $.Msg(event);
    }
    //Listen for hacky inventory updates
    GameEvents.Subscribe("inventory_updated", onSteamInventoryChanged);
    //Listen to inventory updates
    //"dota_inventory_changed"
    GameEvents.Subscribe("dota_inventory_changed", onInventoryChanged);
    GameEvents.Subscribe("dota_inventory_item_changed", onInventoryChanged);
    GameEvents.Subscribe("dota_player_update_selected_unit", onUnitChanged);
    GameEvents.Subscribe("dota_player_update_query_unit", onUnitChanged);
    function onEntityKilled(event) {
        $("#lhd-value").SetDialogVariableInt("lasthits", Players.GetLastHits(Players.GetLocalPlayer()));
        $("#lhd-value").SetDialogVariableInt("denies", Players.GetDenies(Players.GetLocalPlayer()));
    }
    GameEvents.Subscribe("entity_killed", onEntityKilled);
    function onHeroDeath(event) {
        $("#kda-value").SetDialogVariableInt("kills", Players.GetKills(Players.GetLocalPlayer()));
        $("#kda-value").SetDialogVariableInt("deaths", Players.GetDeaths(Players.GetLocalPlayer()));
        $("#kda-value").SetDialogVariableInt("assists", Players.GetAssists(Players.GetLocalPlayer()));
    }
    GameEvents.Subscribe("dota_player_kill", onHeroDeath);
    //Listen to gold updates
    //"dota_money_changed"
    GameEvents.Subscribe("dota_money_changed", onGoldChanged);
    //Listen to shop changes (shop button glow) (should this be done globally in hud.js applied to ZooHud?)
    //"dota_player_shop_changed"
    GameEvents.Subscribe("dota_player_shop_changed", onShopChanged);
    //Listen to glyph updates
    //"dota_glyph_used"
    onEntityKilled(null);
    onHeroDeath(null);
    var items = [];
    for (var i = 0; i < 12; i++) {
        //ROW 0 unless otherwise specified
        var parent_1 = $("#row0");
        if (i > 5) {
            //STASH
            continue; //TODO: make
        }
        else if (i > 2) {
            //ROW 1
            parent_1 = $("#row1");
        }
        items[i] = new ItemPanel(parent_1, i);
    }
})();
